<?php

use Illuminate\Database\Seeder;

class SolicitudSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         $solicitudes = [
            '0' => [
                'codigo' => 'INSP001',
                'fecha' => '2018-04-19 15:21:00',
                'frecuencia' => 'Semanal',
                'observaciones' => "Observacion INSP01",
                'visitas' => 'visitas al cliente',
                'valor_plan_saneamiento' => 180000,
                'frecuencia_visitas' => '8_dias',
                'observaciones_visitas' => 'observaciones',
                'detalle_servicios' => 'detalle de servcios',
                'total_detalle_servicios' => 180000,
                'tipo_facturacion' => 'sc',
                'forma_pago' => 'contado',
                'contrato' => 0,
                'residencias' => 'residencias de cliente',
                'cant_lampara_lamina' => 1,
                'cant_lampara_insectocutora' => 1,
                'cant_trampas' => 1,
                'cant_jaulas' => 1,
                'cant_estaciones_roedor' => 1,
                'observaciones_estaciones' => 'observaciones',
                'cant_cajas_alca_elec' => 1,
                'sumideros' => 1,
                'compra_dispositivos' => 'dispositivo 1',
                'dispositivos_comodato' => 'comodato 1',
                'gestion_calidad' => 'doc 10',
                'areas' => 'areas',
                'cliente_id' => 1,
                'sede_id' => 1,
                'created_at' => '2018-04-19 15:21:00',
                'updated_at' => '2018-04-20 20:21:00'
            ],

            '1' => [
                'codigo' => 'INSP003',
                'fecha' => '2018-04-19 15:21:00',
                'frecuencia' => 'Mensual',
                'observaciones' => "Observacion INSP03",
                'visitas' => 'visitas al cliente',
                'valor_plan_saneamiento' => 180000,
                'frecuencia_visitas' => '8_dias',
                'observaciones_visitas' => 'observaciones',
                'detalle_servicios' => 'detalle de servcios',
                'total_detalle_servicios' => 180000,
                'tipo_facturacion' => 'sc',
                'forma_pago' => 'contado',
                'contrato' => 0,
                'residencias' => 'residencias de cliente',
                'cant_lampara_lamina' => 1,
                'cant_lampara_insectocutora' => 1,
                'cant_trampas' => 1,
                'cant_jaulas' => 1,
                'cant_estaciones_roedor' => 1,
                'observaciones_estaciones' => 'observaciones',
                'cant_cajas_alca_elec' => 1,
                'sumideros' => 1,
                'compra_dispositivos' => 'dispositivo 1',
                'dispositivos_comodato' => 'comodato 1',
                'gestion_calidad' => 'doc 10',
                'areas' => 'areas',
                'cliente_id' => 2,
                'sede_id' => 0,
                'created_at' => '2018-05-19 15:21:00',
                'updated_at' => '2018-05-20 20:21:00'
            ],

            '2' => [
                'codigo' => 'INSP004',
                'fecha' => '2018-04-19 15:21:00',
                'frecuencia' => 'Bimestral',
                'observaciones' => "Observacion INSP04",
                'visitas' => 'visitas al cliente',
                'valor_plan_saneamiento' => 180000,
                'frecuencia_visitas' => '8_dias',
                'observaciones_visitas' => 'observaciones',
                'detalle_servicios' => 'detalle de servcios',
                'total_detalle_servicios' => 180000,
                'tipo_facturacion' => 'sc',
                'forma_pago' => 'contado',
                'contrato' => 0,
                'residencias' => 'residencias de cliente',
                'cant_lampara_lamina' => 1,
                'cant_lampara_insectocutora' => 1,
                'cant_trampas' => 1,
                'cant_jaulas' => 1,
                'cant_estaciones_roedor' => 1,
                'observaciones_estaciones' => 'observaciones',
                'cant_cajas_alca_elec' => 1,
                'sumideros' => 1,
                'compra_dispositivos' => 'dispositivo 1',
                'dispositivos_comodato' => 'comodato 1',
                'gestion_calidad' => 'doc 10',
                'areas' => 'areas',
                'cliente_id' => 3,
                'sede_id' => 0,
                'created_at' => '2018-02-19 15:21:00',
                'updated_at' => '2018-02-20 20:21:00'
            ],

            '3' => [
                'codigo' => 'INSP005',
                'cliente_id' => 4,
                'fecha' => '2018-04-19 15:21:00',
                'frecuencia' => 'Trimestral',
                'observaciones' => "Observacion INSP05",
                'visitas' => 'visitas al cliente',
                'valor_plan_saneamiento' => 180000,
                'frecuencia_visitas' => '8_dias',
                'observaciones_visitas' => 'observaciones',
                'detalle_servicios' => 'detalle de servcios',
                'total_detalle_servicios' => 180000,
                'tipo_facturacion' => 'sc',
                'forma_pago' => 'contado',
                'contrato' => 0,
                'residencias' => 'residencias de cliente',
                'cant_lampara_lamina' => 1,
                'cant_lampara_insectocutora' => 1,
                'cant_trampas' => 1,
                'cant_jaulas' => 1,
                'cant_estaciones_roedor' => 1,
                'observaciones_estaciones' => 'observaciones',
                'cant_cajas_alca_elec' => 1,
                'sumideros' => 1,
                'compra_dispositivos' => 'dispositivo 1',
                'dispositivos_comodato' => 'comodato 1',
                'gestion_calidad' => 'doc 10',
                'areas' => 'areas',
                'sede_id' => 3,
                'created_at' => '2018-02-19 15:21:00',
                'updated_at' => '2018-02-20 20:21:00'
            ],

            '4' => [
                'codigo' => 'INSP006',
                'cliente_id' => 5,
                'fecha' => '2018-04-19 15:21:00',
                'frecuencia' => 'Semestral',
                'observaciones' => "Observacion INSP06",
                'visitas' => 'visitas al cliente',
                'valor_plan_saneamiento' => 180000,
                'frecuencia_visitas' => '8_dias',
                'observaciones_visitas' => 'observaciones',
                'detalle_servicios' => 'detalle de servcios',
                'total_detalle_servicios' => 180000,
                'tipo_facturacion' => 'sc',
                'forma_pago' => 'contado',
                'contrato' => 0,
                'residencias' => 'residencias de cliente',
                'cant_lampara_lamina' => 1,
                'cant_lampara_insectocutora' => 1,
                'cant_trampas' => 1,
                'cant_jaulas' => 1,
                'cant_estaciones_roedor' => 1,
                'observaciones_estaciones' => 'observaciones',
                'cant_cajas_alca_elec' => 1,
                'sumideros' => 1,
                'compra_dispositivos' => 'dispositivo 1',
                'dispositivos_comodato' => 'comodato 1',
                'gestion_calidad' => 'doc 10',
                'areas' => 'areas',
                'sede_id' => 5,
                'created_at' => '2018-02-19 15:21:00',
                'updated_at' => '2018-02-20 20:21:00'
            ],

            '5' => [
                'codigo' => 'INSP007',
                'cliente_id' => 6,
                'fecha' => '2018-04-19 15:21:00',
                'frecuencia' => 'Anual',
                'observaciones' => "Observacion INSP06",
                'visitas' => 'visitas al cliente',
                'valor_plan_saneamiento' => 180000,
                'frecuencia_visitas' => '8_dias',
                'observaciones_visitas' => 'observaciones',
                'detalle_servicios' => 'detalle de servcios',
                'total_detalle_servicios' => 180000,
                'tipo_facturacion' => 'sc',
                'forma_pago' => 'contado',
                'contrato' => 0,
                'residencias' => 'residencias de cliente',
                'cant_lampara_lamina' => 1,
                'cant_lampara_insectocutora' => 1,
                'cant_trampas' => 1,
                'cant_jaulas' => 1,
                'cant_estaciones_roedor' => 1,
                'observaciones_estaciones' => 'observaciones',
                'cant_cajas_alca_elec' => 1,
                'sumideros' => 1,
                'compra_dispositivos' => 'dispositivo 1',
                'dispositivos_comodato' => 'comodato 1',
                'gestion_calidad' => 'doc 10',
                'areas' => 'areas',
                'sede_id' => 0,
                'created_at' => '2018-02-19 15:21:00',
                'updated_at' => '2018-02-20 20:21:00'
            ]
        ];
        DB::table('solicitudes')->insert($solicitudes);
    }
}
